name: 'Check Vultr Secrets'
description: 'Test action to verify Vultr secrets are present.'
runs:
  using: 'composite'
  steps:
    - name: Check VULTR_API_KEY
      run: |
        if [ -z "$VULTR_API_KEY" ]; then
          echo "VULTR_API_KEY is not set!" && exit 1
        fi
      shell: bash
    - name: Check VULTR_REGISTRY_URL
      run: |
        if [ -z "$VULTR_REGISTRY_URL" ]; then
          echo "VULTR_REGISTRY_URL is not set!" && exit 1
        fi
      shell: bash
    - name: Check VULTR_REGISTRY_NAME
      run: |
        if [ -z "$VULTR_REGISTRY_NAME" ]; then
          echo "VULTR_REGISTRY_NAME is not set!" && exit 1
        fi
      shell: bash
    - name: Check VULTR_USER
      run: |
        if [ -z "$VULTR_USER" ]; then
          echo "VULTR_USER is not set!" && exit 1
        fi
      shell: bash
