name: Check Vultr Secrets on Push

on:
  push:
    branches:
      - '**'

jobs:
  check-vultr-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Vultr Secrets Check
        uses: ./.github/actions/check-vultr-secrets
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
          VULTR_REGISTRY_URL: ${{ secrets.VULTR_REGISTRY_URL }}
          VULTR_REGISTRY_NAME: ${{ secrets.VULTR_REGISTRY_NAME }}
          VULTR_USER: ${{ secrets.VULTR_USER }}