name: Check Vultr Secrets on Push

on:
  push:
    branches:
      - '**'

jobs:
  check-vultr-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Vultr Secrets Check
        uses: ./.github/actions/check-vultr-secrets
